---

- name: Install Packages (all nodes)
  yum: name={{ item }}
  with_items:
    - httpd
  notify:
    - apache restart
  tags:
    - all_nodes

- name: apache restart
  service: name=httpd state=restarted enabled=true

- name: Install Packages (master node)
  yum: name={{ item }}
  with_items:
    - haproxy
  tags:
    - master_node


